col = [ 'blue','yellow','green','red','black','tired','sleepy','arrogant','angry','shy' ]

row = [ 'eagle','puppy','rabbit','dolphin','swan','president','mother','father','child','doctor' ]

animals = ['eagle','puppy','rabbit','dolphin','swan']
people = ['president','mother','father','child','doctor']
colors = ['blue','yellow','green','red','black']
adjectives = ['tired','sleepy','arrogant','angry','shy']
actions = ['has landed','is waiting','walks alone','is in danger']

places = {
'amusement park':'bashful',
'batting cage':'gross',
'crater':'cautious',
'dentist office':'happy',
'entrance':'upset',
'fair':'pink',
'grotto':'annoyed',
'hotel':'rude',
'igloo':'anxious',
'juice bar':'boring',
'kansas':'well made',
'lobby':'cute',
'moon':'cold',
'nuclear reactor':'wooden',
'orbit':'obsolete',
'pier':'free',
'quarry':'black',
'restroom':'mean',
'seventh floor':'modern',
'tunnel':'terrible',
'underground':'quick',
'virtual reality':'turbulent',
'wind tunnel':'fake',
'fort ticonderoga':'violent',
'nightclub':'great',
'zoo':'imaginary'}

chart = { 
repr(['blue','eagle']):'interviewer',
repr(['blue','puppy']):'mailman',
repr(['blue','rabbit']):'cat',
repr(['blue','dolphin']):'apple',
repr(['blue','swan']):'chef',
repr(['blue','president']):'toast',
repr(['blue','mother']):'toothpick',
repr(['blue','father']):'puppy',
repr(['blue','child']):'worker',
repr(['blue','doctor']):'orange',

repr(['yellow', 'eagle']):'wave',
repr(['yellow', 'puppy']):'couch',
repr(['yellow', 'rabbit']):'fish',
repr(['yellow', 'dolphin']):'van',
repr(['yellow', 'swan']):'marble',
repr(['yellow', 'president']):'butter',
repr(['yellow', 'mother']):'boot',
repr(['yellow', 'father']):'donkey',
repr(['yellow', 'child']):'squirrel',
repr(['yellow', 'doctor']):'chair',

repr(['green', 'eagle']):'fence',
repr(['green', 'puppy']):'house',
repr(['green', 'rabbit']):'oven',
repr(['green', 'dolphin']):'pillow',
repr(['green', 'swan']):'berry',
repr(['green', 'president']):'fruit',
repr(['green', 'mother']):'stew',
repr(['green', 'father']):'chicken',
repr(['green', 'child']):'carrot',
repr(['green', 'doctor']):'nose',

repr(['red', 'eagle']):'book',
repr(['red', 'puppy']):'hook',
repr(['red', 'rabbit']):'foot',
repr(['red', 'dolphin']):'butler',
repr(['red', 'swan']):'general',
repr(['red', 'president']):'sailboat',
repr(['red', 'mother']):'straw',
repr(['red', 'father']):'tongue',
repr(['red', 'child']):'hand',
repr(['red', 'doctor']):'maid',

repr(['black', 'eagle']):'novel',
repr(['black', 'puppy']):'blanket',
repr(['black', 'rabbit']):'football',
repr(['black', 'dolphin']):'wine',
repr(['black', 'swan']):'painting',
repr(['black', 'president']):'sculpture',
repr(['black', 'mother']):'milkshake',
repr(['black', 'father']):'spaniard',
repr(['black', 'child']):'warrior',
repr(['black', 'doctor']):'toad',

repr(['tired', 'eagle']):'soldier',
repr(['tired', 'puppy']):'taco',
repr(['tired', 'rabbit']):'magician',
repr(['tired', 'dolphin']):'screw',
repr(['tired', 'swan']):'baby',
repr(['tired', 'president']):'daycare',
repr(['tired', 'mother']):'unicorn',
repr(['tired', 'father']):'pizza',
repr(['tired', 'child']):'woman',
repr(['tired', 'doctor']):'sunrise',

repr(['sleepy', 'eagle']):'sword',
repr(['sleepy', 'puppy']):'rifle',
repr(['sleepy', 'rabbit']):'camp',
repr(['sleepy', 'dolphin']):'phone',
repr(['sleepy', 'swan']):'matchstick',
repr(['sleepy', 'president']):'hose',
repr(['sleepy', 'mother']):'committee',
repr(['sleepy', 'father']):'fog',
repr(['sleepy', 'child']):'city',
repr(['sleepy', 'doctor']):'tent',

repr(['arrogant', 'eagle']):'bike',
repr(['arrogant', 'puppy']):'scarecrow',
repr(['arrogant', 'rabbit']):'bomb',
repr(['arrogant', 'dolphin']):'wind',
repr(['arrogant', 'swan']):'bucket',
repr(['arrogant', 'president']):'gentleman',
repr(['arrogant', 'mother']):'rapper',
repr(['arrogant', 'father']):'peanut',
repr(['arrogant', 'child']):'torpedo',
repr(['arrogant', 'doctor']):'cactus',

repr(['angry', 'eagle']):'farmer',
repr(['angry', 'puppy']):'banker',
repr(['angry', 'rabbit']):'record',
repr(['angry', 'dolphin']):'windmill',
repr(['angry', 'swan']):'surfer',
repr(['angry', 'president']):'mushroom',
repr(['angry', 'mother']):'river',
repr(['angry', 'father']):'spider',
repr(['angry', 'child']):'ocean',
repr(['angry', 'doctor']):'governor',

repr(['shy', 'eagle']):'aunt',
repr(['shy', 'puppy']):'comedian',
repr(['shy', 'rabbit']):'pen',
repr(['shy', 'dolphin']):'rose',
repr(['shy', 'swan']):'museum',
repr(['shy', 'president']):'crocodile',
repr(['shy', 'mother']):'cow',
repr(['shy', 'father']):'test',
repr(['shy', 'child']):'bullet',
repr(['shy', 'doctor']):'pickle'
}
